PRACTISE QUESTIONs

In [1]:
import numpy as np

1. create 5*5 matrix and print the middle 3*3 matrix


In [9]:
arr = np.random.random(25).reshape(5,5)
print(arr)
arr2=[]


for i in range(len(arr)):
    for j in range(len(arr[0])):
        if i==0 or i==(len(arr)-1):
            break
        else:
            if (j==0) or (j==(len(arr[0])-1)):
                continue
            else:
                arr2.append(arr[i][j])
np.array(arr2).reshape(3,3)
    



[[0.96003394 0.56870021 0.14109863 0.93328024 0.22984999]
 [0.94491272 0.35050288 0.34480052 0.70607738 0.52984506]
 [0.43309102 0.01210983 0.70438741 0.11560726 0.27571329]
 [0.43436794 0.89390798 0.64276436 0.7968678  0.7377052 ]
 [0.00922562 0.91510502 0.01285736 0.48436909 0.49980205]]


array([[0.35050288, 0.34480052, 0.70607738],
       [0.01210983, 0.70438741, 0.11560726],
       [0.89390798, 0.64276436, 0.7968678 ]])

2.Concatenate two 1-dimensional arrays of length 5.

In [16]:
a = np.arange(4).reshape(2,2)
b = np.arange(4).reshape(2,2)
print(a,b)
print(np.concatenate((a,b), axis=0))# rows
print(np.concatenate((a,b), axis=1))#cols

[[0 1]
 [2 3]] [[0 1]
 [2 3]]
[[0 1]
 [2 3]
 [0 1]
 [2 3]]
[[0 1 0 1]
 [2 3 2 3]]


3. Create a 5x5 matrix with random integers. Find the maximum, minimum, and mean of the matrix.

In [20]:
mat = np.random.randint(1,25,(5,5))
print(np.max(mat))
print(np.min(mat))
print(np.mean(mat))
print(np.std(mat))
print(np.sqrt(mat))
print(np.log(mat))


24
1
11.32
7.508501847905479
[[2.82842712 1.         3.74165739 1.         4.12310563]
 [2.82842712 3.46410162 1.         3.60555128 4.47213595]
 [4.79583152 2.44948974 1.41421356 4.12310563 4.35889894]
 [4.89897949 2.23606798 4.47213595 1.73205081 4.69041576]
 [3.         4.35889894 2.82842712 2.         2.64575131]]
[[2.07944154 0.         2.63905733 0.         2.83321334]
 [2.07944154 2.48490665 0.         2.56494936 2.99573227]
 [3.13549422 1.79175947 0.69314718 2.83321334 2.94443898]
 [3.17805383 1.60943791 2.99573227 1.09861229 3.09104245]
 [2.19722458 2.94443898 2.07944154 1.38629436 1.94591015]]


4. Create an array of 100 random values from a normal distribution and compute the 25th, 50th, and 75th percentiles.


solution: 1. sort the data in assending order
         

  2. calculate the rank(R) = P*(N+1) {where P = percentile(25%), N= len of the array}
        
  3. if the R is integeger then the value at the percentile is the arr[R]

  4. if R is not an inetger for example 1.5 then the value at the perentile is average(arr[1],arr[2])

In [27]:
random_array = np.array(np.random.randint(1,10,(10)))
print(random_array)
percentiles = np.percentile(random_array,[25,50])
print(percentiles)

[8 1 5 3 1 2 8 8 7 1]
[1.25 4.  ]


COMCEPT OF BOOLEAN INDEXING

arr[arr%2==0] --> this prints all the even numbers in the array travelling all the elements

In [29]:
barr = np.array(np.random.randint(1,10,(6)))
print(barr)
barr[barr%2==0]

[3 1 7 8 2 3]


array([8, 2], dtype=int32)