In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
l= [1,2,3,4]
arr = np.array(l)
print(arr)

[1 2 3 4]


In [4]:
type(arr)

numpy.ndarray

In [5]:
l2 = [[1,2,3],[4,5,6]]
arr2 = np.array(l2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
print(arr.transpose())
print(arr2.transpose())


[1 2 3 4]
[[1 4]
 [2 5]
 [3 6]]


In [7]:
print(np.empty((3,4),dtype = int))


[[      3112641647160                  57                   0
                    0]
 [       223338299392 7074711247546115435 3256721973914712373
  3847820301160637797]
 [3759720871130901861 3486684624719458353 7162263158364976484
  8462385098680267893]]


In [8]:
print(np.ones((3,3),dtype = bool))
print(np.zeros((3,3),dtype = bool))


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[False False False]
 [False False False]
 [False False False]]


In [9]:
a = np.arange(1,51)
b = np.arange(1,101,2)
print(len(a),len(b))
print(a)
print(b)


50 50
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [10]:
a1 = a.reshape(10,5)
b1 = b.reshape(5,10)
print(a1)
print(b1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]]


FLATTEN AND RAVEL

Flatten doenot change the actual array but Ravel changes the actual array


In [14]:
a2 = a1.flatten()
b2 = b1.ravel()

a2[1] = 0
b2[1] = 0

print(a1,a2)
print(b1,b2)




[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]] [ 1  0  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
[[ 1  0  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]
 [41 43 45 47 49 51 53 55 57 59]
 [61 63 65 67 69 71 73 75 77 79]
 [81 83 85 87 89 91 93 95 97 99]] [ 1  0  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


NUMPY MATHEMATICAL OPERATIONS

In [18]:
x = np.arange(1,26).reshape(5,5)
y = np.arange(1,51,2).reshape(5,5)

print(np.add(x,y), x+y)
print(np.subtract(x,y), x-y)
print(np.multiply(x,y),x*y)
print(x/y)

print(x@y)


[[ 2  5  8 11 14]
 [17 20 23 26 29]
 [32 35 38 41 44]
 [47 50 53 56 59]
 [62 65 68 71 74]] [[ 2  5  8 11 14]
 [17 20 23 26 29]
 [32 35 38 41 44]
 [47 50 53 56 59]
 [62 65 68 71 74]]
[[  0  -1  -2  -3  -4]
 [ -5  -6  -7  -8  -9]
 [-10 -11 -12 -13 -14]
 [-15 -16 -17 -18 -19]
 [-20 -21 -22 -23 -24]] [[  0  -1  -2  -3  -4]
 [ -5  -6  -7  -8  -9]
 [-10 -11 -12 -13 -14]
 [-15 -16 -17 -18 -19]
 [-20 -21 -22 -23 -24]]
[[   1    6   15   28   45]
 [  66   91  120  153  190]
 [ 231  276  325  378  435]
 [ 496  561  630  703  780]
 [ 861  946 1035 1128 1225]] [[   1    6   15   28   45]
 [  66   91  120  153  190]
 [ 231  276  325  378  435]
 [ 496  561  630  703  780]
 [ 861  946 1035 1128 1225]]
[[1.         0.66666667 0.6        0.57142857 0.55555556]
 [0.54545455 0.53846154 0.53333333 0.52941176 0.52631579]
 [0.52380952 0.52173913 0.52       0.51851852 0.51724138]
 [0.51612903 0.51515152 0.51428571 0.51351351 0.51282051]
 [0.51219512 0.51162791 0.51111111 0.5106383  0.51020408]]
[[ 415  445  

In [19]:
print(np.sum(b,axis=0))


2497


In [20]:
print(np.pi)

3.141592653589793


In [26]:
print(np.sin(0))

0.0


In [27]:
print(np.random.random())

0.22680659390731284


In [33]:
np.random.random(2)

array([0.16459065, 0.4588154 ])

In [44]:
np.random.random((2,4))

array([[0.05597297, 0.43047166, 0.46753183, 0.87191029],
       [0.84619097, 0.12674219, 0.07169001, 0.63851148]])

In [52]:
np.random.randint(4,6)

5

In [53]:
np.random.randint(1,10,(1,5))

array([[4, 1, 8, 7, 1]], dtype=int32)

In [59]:
np.random.rand(2,2)


array([[0.85785521, 0.27332182],
       [0.73366591, 0.29810682]])

In [60]:
np.random.randn(2,2)

array([[ 1.00971602,  0.90751758],
       [-1.05025887, -1.20392525]])

In [67]:
ax = np.arange(1,51).reshape(5,10).flatten()
np.random.choice(ax)

np.int64(28)

In [70]:
str1 = "Iam Abhilash"
str2 = " \n and I love Shweta"

np.char.add(str1,str2)


np.str_('Iam Abhilash \n and I love Shweta')

In [72]:
np.char.split(np.char.add(str1,str2))

array(list(['Iam', 'Abhilash', 'and', 'I', 'love', 'Shweta']),
      dtype=object)

In [73]:
np.char.splitlines(np.char.add(str1,str2))

array(list(['Iam Abhilash ', ' and I love Shweta']), dtype=object)

In [76]:
np.char.center("abhi", 20, "s")

array('ssssssssabhissssssss', dtype='<U20')